apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimessage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apimessage
  template:
    metadata:
      labels:
        app: apimessage
    spec:
      containers:
      - name: apimessage
        image: luizcssoares/apimessage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apimessage
spec:
  selector:
    app: apimessage
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
